from django.conf.urls import url
from . import views


urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^product/', views.product, name='product'),
        url(r'^book/', views.book, name='book'),
        url(r'^appoint/', views.appoint, name='appoint'),
        url(r'^contact/', views.contact, name='contact'),
        url(r'^login/', views.login, name='login'),
        url(r'^loginForm/', views.loginForm, name='loginForm'),
        url(r'^alogin/', views.alogin, name='alogin'),
        url(r'^aloginForm/', views.aloginForm, name='aloginForm'),
        url(r'^register/', views.register, name='register'),
        url(r'^registerForm/', views.registerForm, name='registerForm'),
        url(r'^cart/', views.cart, name='cart'),
        url(r'^YourCart/', views.YourCart, name='YourCart'),
        url(r'^addToCart/', views.addToCart, name='addToCart'),
        url(r'^category/', views.category, name='category'),
        url(r'^aboutproduct/', views.aboutproduct, name='aboutproduct'),
        url(r'^remove/', views.remove, name='remove'),
        url(r'^logout/', views.logout, name='logout'),
        url(r'^alogout/', views.alogout, name='alogout'),
        url(r'^addItem/', views.addItem, name='addItem'),
        url(r'^caddItem/', views.caddItem, name='caddItem'),
        url(r'^removeItem/', views.removeItem, name='removeItem'),
        url(r'^removeFromCart/', views.removeFromCart, name='removeFromCart'),
        url(r'^clearcart/', views.clearcart, name='clearcart'),
        url(r'^aregister/', views.aregister, name='aregister'),
        url(r'^aregisterForm/', views.aregisterForm, name='aregisterForm'),
        url(r'^update/(?P<productId>\d+)/$', views.update, name='update'),
        url(r'^DoctorRegister/', views.DoctorRegister, name='DoctorRegister'),
        url(r'^DoctorLogin/', views.DoctorLogin, name='DoctorLogin'),
        url(r'^DoctorLoginForm/', views.DoctorLoginForm, name='DoctorLoginForm'),
        url(r'^DoctorPage/', views.DoctorPage, name='DoctorPage'),
        url(r'^DoctorLogout/', views.DoctorLogout, name='DoctorLogout'),
        url(r'^DoctorDetail/', views.DoctorDetail, name='DoctorDetail'),
        url(r'^CancelAppointment/', views.CancelAppointment, name='CancelAppointment'),
        url(r'^ConfirmAppointment/', views.ConfirmAppointment, name='ConfirmAppointment'),
]